// Generated by CoffeeScript 1.4.0
(function() {

  window.Ammunition = (function() {

    Ammunition.prototype.STEP = 0;

    Ammunition.prototype.WIDTH = 40;

    Ammunition.prototype.HEIGHT = 40;

    function Ammunition(person, blocks, x, y) {
      this.person = person;
      this.blocks = blocks;
      this.x = x;
      this.y = y;
      this.width = this.WIDTH;
      this.height = this.HEIGHT;
      this.isAlive = true;
    }

    Ammunition.prototype.move = function() {
      return this.destroyIfBumpedToPerson(this.person);
    };

    Ammunition.prototype.isNextXStepMoreThanEdge = function(edge) {
      return this.x + this.width >= edge;
    };

    Ammunition.prototype.isNextYStepMoreThanEdge = function(edge) {
      return this.y + this.height >= edge;
    };

    Ammunition.prototype.isNextXStepLessThanEdge = function(edge) {
      return this.x <= edge;
    };

    Ammunition.prototype.isNextYStepLessThanEdge = function(edge) {
      return this.y <= edge;
    };

    Ammunition.prototype.isPersonOnTheRightSide = function(edge) {
      return this.x >= edge;
    };

    Ammunition.prototype.isPersonOnTheLeftSide = function(edge) {
      return this.x + this.width <= edge;
    };

    Ammunition.prototype.isPersonHigher = function(edge) {
      return this.y + this.height <= edge;
    };

    Ammunition.prototype.isPersonLower = function(edge) {
      return this.y >= edge;
    };

    Ammunition.prototype.isPersonOnTheLineOfBlock = function(block) {
      return (this.y + this.height >= block.y && this.y + this.height <= block.y + block.height) || (this.y <= block.y + block.height && this.y >= block.y);
    };

    Ammunition.prototype.isPersonOnTheRowOfBlock = function(block) {
      return (this.x + this.width >= block.x && this.x + this.width <= block.x + block.width) || (this.x <= block.x + block.width && this.x >= block.x);
    };

    Ammunition.prototype.destroyIfBumpedToPerson = function(person) {
      var h0, h1, w0, w1, x0, x1, y0, y1;
      x0 = this.x;
      y0 = this.y;
      w0 = this.width;
      h0 = this.height;
      x1 = this.person.x;
      y1 = this.person.y;
      w1 = this.person.width;
      h1 = this.person.height;
      if (x0 < x1 && x0 + w0 > x1 && (y1 + h1 > y0 && y1 < y0 || y1 > y0 && y1 < y0 + h0) || x1 < x0 && x1 + w1 > x0 && (y1 < y0 && y1 + h1 > y0 || y1 > y0 && y1 < y0 + h0)) {
        this.person.bulletCount += 2;
        return this.isAlive = false;
      }
    };

    return Ammunition;

  })();

}).call(this);
