// Generated by CoffeeScript 1.4.0
(function() {

  window.Block = (function() {

    function Block(x, y, width, height) {
      this.x = x;
      this.y = y;
      this.width = width;
      this.height = height;
    }

    return Block;

  })();

}).call(this);
