// Generated by CoffeeScript 1.4.0
(function() {

  window.Painter = (function() {

    function Painter(context, canvasWidth, canvasHeight, person, ghosts, blocks, bullets, lines, ammunitions, picsLoader, paddingTop) {
      this.context = context;
      this.canvasWidth = canvasWidth;
      this.canvasHeight = canvasHeight;
      this.person = person;
      this.ghosts = ghosts;
      this.blocks = blocks;
      this.bullets = bullets;
      this.lines = lines;
      this.ammunitions = ammunitions;
      this.picsLoader = picsLoader;
      this.paddingTop = paddingTop;
    }

    Painter.prototype.repaint = function(frameNumber, gameState) {
      var ammunition, block, bullet, ghost, pattern, pic, text, _i, _j, _k, _l, _len, _len1, _len2, _len3, _ref, _ref1, _ref2, _ref3;
      if (gameState === "intro") {
        pic = this.picsLoader.picsSet.intro;
        this.context.drawImage(pic, 0, 0);
        return;
      }
      pattern = this.context.createPattern(this.picsLoader.picsSet.gameBackground, "repeat");
      this.context.fillStyle = pattern;
      this.context.fillRect(0, 0, this.canvasWidth, this.canvasHeight);
      pic = this.picsLoader.picsSet.person;
      this.context.drawImage(pic, 0, 0, this.person.width, this.person.height, this.person.x, this.person.y, this.person.width, this.person.height);
      _ref = this.ghosts;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        ghost = _ref[_i];
        pic = this.picsLoader.picsSet["ghost" + ghost.picNumber];
        this.context.drawImage(pic, 0, 0, ghost.width, ghost.height, ghost.x, ghost.y, ghost.width, ghost.height);
      }
      pattern = this.context.createPattern(this.picsLoader.picsSet.blockBackground, "repeat");
      this.context.fillStyle = pattern;
      _ref1 = this.blocks;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        block = _ref1[_j];
        this.context.fillRect(block.x, block.y, block.width, block.height);
      }
      pic = this.picsLoader.picsSet.bullet;
      _ref2 = this.bullets;
      for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
        bullet = _ref2[_k];
        this.context.drawImage(pic, 0, 0, 20, 20, bullet.x, bullet.y, 20, 20);
      }
      pic = this.picsLoader.picsSet.ammunition;
      _ref3 = this.ammunitions;
      for (_l = 0, _len3 = _ref3.length; _l < _len3; _l++) {
        ammunition = _ref3[_l];
        this.context.drawImage(pic, 0, 0, 40, 40, ammunition.x, ammunition.y, 40, 40);
      }
      pattern = this.context.createPattern(this.picsLoader.picsSet.blockBackground, "repeat");
      this.context.fillStyle = pattern;
      this.context.fillRect(0, this.canvasHeight, this.canvasWidth, this.paddingTop);
      this.context.fillStyle = "rgba(0, 0, 0, 0.5)";
      this.context.fillRect(this.canvasWidth / 2 - 12, this.canvasHeight + this.paddingTop / 3 - 8, 40, 40);
      this.context.fillRect(225, this.canvasHeight + this.paddingTop / 4, 40, 40);
      text = Math.floor(frameNumber / 25);
      this.context.fillStyle = "#FFFFFF";
      this.context.font = "normal 28px sans-serif";
      this.context.textBaseline = 'top';
      this.context.fillText(text, this.canvasWidth / 2, this.canvasHeight + this.paddingTop / 3);
      this.context.fillText(this.person.bulletCount, this.canvasWidth / 3, this.canvasHeight + this.paddingTop / 3);
      pic = this.picsLoader.picsSet.ammunition;
      this.context.drawImage(pic, 0, 0, 40, 40, 185, this.canvasHeight + this.paddingTop / 4, 40, 40);
      if (gameState === "gameNotStarted") {
        this.context.fillStyle = "rgba(0, 0, 0, 0.5)";
        this.context.fillRect(25, 75, 660, 500);
        this.context.fillStyle = "#FFFFFF";
        this.context.font = "normal 50px sans-serif";
        this.context.textBaseline = 'top';
        this.context.fillText("Твоя цель - продержаться", 50, 100);
        this.context.fillText("как можно дольше.", 180, 200);
        this.context.fillText("Чтобы начать,", 180, 300);
        this.context.fillText("жми пробел.", 200, 400);
        this.context.font = "normal 20px sans-serif";
        this.context.fillText("Менять направление - стрелки.", 25, 500);
        this.context.fillText("Стрелять - пробел.", 25, 525);
      }
      if (gameState === "gameFinished") {
        this.context.fillStyle = "rgba(0, 0, 0, 0.5)";
        this.context.fillRect(25, 75, 660, 450);
        this.context.fillStyle = "#FFFFFF";
        this.context.font = "normal 50px sans-serif";
        this.context.textBaseline = 'top';
        this.context.fillText("Ты продержался " + text + " с.", 100, 100);
        this.context.fillText("Заново?", 200, 200);
        this.context.fillText("Жми пробел.", 180, 300);
        this.context.font = "normal 20px sans-serif";
        return this.context.fillText("Не забудь запостить результат на joyreactor :)", 100, 400);
      }
    };

    return Painter;

  })();

  /*@context.fillStyle = "#000000"
  for line in @lines
  @context.beginPath()
  @context.moveTo(line.startPoint.x, line.startPoint.y)
  @context.lineTo(line.endPoint.x, line.endPoint.y)
  @context.stroke()
  */


}).call(this);
