// Generated by CoffeeScript 1.4.0
(function() {

  window.PicsLoader = (function() {

    function PicsLoader() {
      this.picsSet = {
        gameBackground: this.loadPic("gameBackground", "graphics/gameBackground.jpg"),
        blockBackground: this.loadPic("blockBackground", "graphics/blockBackground.jpg"),
        ammunition: this.loadPic("ammunition", "graphics/ammunition.jpg"),
        ghost1: this.loadPic("ghost1", "graphics/ghost1.png"),
        ghost2: this.loadPic("ghost2", "graphics/ghost2.png"),
        ghost3: this.loadPic("ghost3", "graphics/ghost3.png"),
        ghost4: this.loadPic("ghost4", "graphics/ghost4.png"),
        person: this.loadPic("person", "graphics/person.png"),
        bullet: this.loadPic("bullet", "graphics/bullet.jpeg"),
        intro: this.loadPic("intro", "graphics/intro.png")
      };
    }

    PicsLoader.prototype.loadPic = function(name, path) {
      var pic;
      pic = new Image();
      pic.isReady = false;
      pic.onload = function() {
        return this.isReady = true;
      };
      pic.src = path;
      return pic;
    };

    PicsLoader.prototype.isReady = function() {
      var key, value, _i, _len, _ref;
      _ref = this.picsSet;
      for (value = _i = 0, _len = _ref.length; _i < _len; value = ++_i) {
        key = _ref[value];
        if (!this.picsSet[key].pic.isReady) {
          return false;
        }
      }
      return true;
    };

    return PicsLoader;

  })();

}).call(this);
